openapi: 3.0.3
info:
  title: Clientes API
  description: |-
    API do microsserviço de Clientes
  version: 0.0.1
paths:
  /api/admin/accounts:
    get:
      summary: List accounts
      description: List all accounts
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
    post:
      summary: Add account
      description: Add new account
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Account"
        '401':
          description: unauthorized
  /api/admin/accounts/{id}:
    get:
      summary: Find account
      description: Find one specific account
      parameters:
        - name: id
          in: path
          description: ID of account that needs to be fetched
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Account"
        '400':
          description: invalid ID supplied
        '404':
          description: not found
    put:
      summary: Update account
      description: Update account by entering the whole updated account
      parameters:
      - name: id
        in: path
        description: ID of account that needs to be updated
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Account"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Account"
        '400':
          description: invalid ID supplied
        '401':
          description: unauthorized
    delete:
      summary: Delete account
      description: Delete account by entering its ID
      parameters:
      - name: id
        in: path
        description: ID of account that needs to be deleted
        required: true
        schema:
          type: string
      responses:
        '204':
          description: no content
        '401':
          description: unauthorized
        '400':
          description: invalid ID supplied
  /api/admin/transactions:
    get:
      summary: List transactions
      description: List all transactions
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Transaction"
    post:
      summary: Add transaction
      description: Add new transaction
      requestBody:
        content:
            application/json:
              schema:
              type: object
              properties:
                valor:
                  type: number
                nomeCartao:
                  type: string
                numeroCartao:
                  type: string
                validadeCartao:
                  type: string
                cvcCartao:
                  type: string
                vencimentoFatura:
                  type: string
              required:
                - valor
                - nomeCartao
                - numeroCartao
                - validadeCartao
                - cvcCartao
                - vencimentoFatura
      responses:
        '201':
          description: Created
          content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
        '303':
          description: See Other
        '400':
          description: Bad Request
  /api/admin/transactions/{id}:
    get:
      summary: Get a transaction by transaction ID
      description: List a transaction by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Transaction"
        '404':
          description: Not Found
    put:
      summary: Update the status of a transaction
      description: Update account by entering the transaction ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
              required:
                - status
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        email:
          type: string
          format: email
        senha:
          type: string
          format: password
    Transaction:
      type: object
      properties:
        idCliente:
          type: string
        status:
          type: string
        valor:
          type: number
        