openapi: 3.0.3
info:
  title: Anti-fraud API
  description: |-
    Microsservice API of Anti-fraud
  version: 0.0.1
paths:
  /api/admin/antiFraud:
    get:
      summary: List analysis anti-fraud with in analysis status
      responses:
        '200':
          description: Return the matched anti-frauds 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AntiFraud"
        '404':
          description: Not found
          content:
            application/json:
              example: "Not found"
                
    post:
      summary: Create new anti-fraud with default value as in analysis
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AntiFraud"
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/AntiFraud"
        '400':
          description: Not created
          content:
            application/json:
              example: "Not created due to information error"
  /api/admin/antiFraud/{id}:
    parameters:
        - name: id
          in: path
          description: ID of the anti-fraud that needs to be fetched
          required: true
          schema:
            type: string
    get:
      summary: Find one specific anti-fraud by id
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/AntiFraudID"
        '404':
          description: invalid ID supplied
          content:
            application/json:
              example: "Not found"
    patch:
      summary: Update the status of a specific anti-fraud
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/AntiFraud"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/AntiFraud"
        '404':
          description: invalid ID supplied
          content:
            application/json:
              example: "Not found"
components:
  schemas:
    AntiFraud:
      type: object
      properties:
        id:
          type: string
        idCliente:
          type: string
        idTransicao:
          type: string
        status:
          type: string
    AntiFraudID:
      type: object
      properties:
        id:
          type: string
        idCliente:
          type: string
        idTransicao:
          type: string
        status:
          type: string
        dadosPessoais:
          type: object
          properties:
            nome:
              type: string
            cpf:
              type: string
            email:
              type: string
            telefone:
              type: string
            rendaMensal:
              type: number
        endereco:
          type: object
          properties:
            rua:
              type: string
            numero:
              oneOf: 
                - type: string
                - type: integer
            complemento:
              oneOf: 
                - type: string
                - type: integer
            cep:
              type: string
            cidade:
              type: string
            uf:
              type: string
        cartao:
          type: object
          properties:
            vencimentoFatura:
              type: string
        Transaction:
          type: object
          properties:
            valor:
              type: number
